routes/web.php
<?php

use Illuminate\Support\Facades\Http;
use Illuminate\Support\Facades\Route;
use PragmaRX\Google2FALaravel\Support\Authenticator;
use Shetabit\Multipay\Invoice;
use Shetabit\Payment\Facade\Payment;
use Tzsk\Sms\Facades\Sms;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('logout', function () {
    \Illuminate\Support\Facades\Auth::logout();
    (new Authenticator(request()))->logout();
    return redirect()->route('login.form');
})->name('logout');
Route::get('/image/{type}/{id}/{file}',
    function ($type, $id, $file) {
        $path = storage_path('app/uploaded/' . $type . '/' . $id . '/' . $file);
        if (!File::exists($path)) {
            abort(404);
        }
        $file = File::get($path);
        $type = File::mimeType($path);
        $response = Response::make($file, 200);
        $response->header("Content-Type", $type);
        return $response;
    })->name('image.view');
Route::get('get-cities', function () {
    $cities = \App\Models\City::select(['id', 'name'])->where('parent', request('id'))->get();
    $html = '<option value="">انتخاب کنید...</option>';
    foreach ($cities as $row) {
        $html .= '<option value="' . $row->id . '">' . $row->name . '</option>';
    }
    return json_encode($html);
})->name('get-cities');
Route::namespace("App\Http\Controllers\Auth")->middleware('guest')->group(function () {
    Route::get('auth/login', 'LoginRegisterController@loginForm')->name('login.form');
    Route::post('auth/login/verify', 'LoginRegisterController@login')->name('login.login');
    Route::get('auth/register', 'LoginRegisterController@register')->name('register.form');
    Route::post('auth/register/store', 'LoginRegisterController@registerStore')->name('register.store');
    Route::get('forget-password', 'LoginRegisterController@forgetPasswordForm')->name('login.forget_password.form');
    Route::post('forget-password', 'LoginRegisterController@forgetPasswordSendEmail')->name('login.forget_password.send');
    Route::post('forget-change-password', 'LoginRegisterController@forgetChangePassword')->name('login.forget_password.change-password');
});
Route::get('verify-email/token/{token}', "App\Http\Controllers\User\StepsController@verifyEmail")->name('step.verify-token.email');
/// Route Landing
Route::namespace("App\Http\Controllers\Landing")->middleware('guest')->group(function () {
    Route::get('/', 'HomeController@index')->name('landing.home');
    Route::get('/join', 'HomeController@test');
    Route::get('/about','HomeController@about')->name('landing.about');
    Route::get('/blog-page','HomeController@blog')->name('landing.blog');
    Route::get('/services','HomeController@services')->name('landing.services');
    Route::get('/faq','HomeController@faq')->name('landing.faq');
    Route::get('/chart','HomeController@chart')->name('landing.chart');
    Route::get('/post/{slug}','HomeController@post_show')->name('landing.post');
    Route::get('/search','HomeController@post_search')->name('landing.search');

});

Route::get('withdraw/token/{token}', "App\Http\Controllers\User\WithdrawController@verifyEmail")->name('verify-withdraw.email');
Route::get('reject/token/{token}', "App\Http\Controllers\User\WithdrawController@rejectEmail")->name('reject-withdraw.email');



///// Route User
Route::middleware(['auth', 'steps', '2fa'])->namespace("App\Http\Controllers\User")->group(function () {
    ///// Route Step
    Route::prefix('step')->group(function () {
        Route::get('verify-mobile', "StepsController@mobile")->name('step.verify-mobile');
        Route::get('verify-email', "StepsController@email")->name('step.verify-email');
        Route::post('verify-mobile/send-verify', "StepsController@sendVerify")->name('step.send-verify');
        Route::post('verify-email/send-link', "StepsController@sendEmail")->name('step.send-email');
        Route::get('information', "StepsController@information")->name('step.information');
        Route::post('information/store', "StepsController@informationStore")->name('step.information.store');
        Route::get('bank', "StepsController@bank")->name('step.bank');
        Route::post('bank/store', "StepsController@bankStore")->name('step.bank.store');
        Route::get('finish', "StepsController@finish")->name('step.finish');
    });

    Route::post('google2fa/authenticate',function (){
        return redirect(\route('user.dashboard'));
    });
    Route::get('dashboard', "HomeController@dashboard")->name('user.dashboard');
    Route::get('profile', "ProfileController@formProfile")->name('user.profile.form');
    Route::get('swap/{unit}', 'SwapController@show')->name('swap.show');
    Route::post('swap', 'SwapController@store')->name('swap.store');
    Route::post('get-unit-price', 'SwapController@get_unit_price')->name('get-unit-price');
    Route::post('get-unit-swap-fee-price', 'SwapController@get_unit_swap_fee_price')->name('get-unit-swap-fee-price');
    Route::post('get_theter_price', 'HomeController@get_theter_price')->name('get_theter_price');
    Route::post('exchange', 'SwapController@exchange')->name('exchange');
    Route::post('createAccount/{unit}', 'ProfileController@wallet')->name('createAccount');
//    Route::post('check-withdraw-amount', 'WithdrawController@check_withdraw_amount')->name('check-withdraw-amount');
//    Route::post('withdraw-from-wallet', 'WithdrawController@withdraw_from_wallet')->name('withdraw-from-wallet');
//    Route::post('send-message-admin', 'WithdrawController@send_message_admin')->name('send-message-admin');
    Route::post('get-total-usdt', 'WithdrawController@get_total_usdt')->name('get-total-usdt');
//    Route::get('withdraw/{unit}','WithdrawController@index')->name('withdraw.index');
//    Route::post('withdraw','WithdrawController@store')->name('withdraw.store');
    Route::get('withdraw/token/{token}', "WithdrawController@verifyEmail")->name('verify-withdraw.email');
    Route::get('reject/token/{token}', "WithdrawController@rejectEmail")->name('reject-withdraw.email');
    Route::get('change-pass', 'ProfileController@change_pass_view')->name('change_pass.index');
    Route::post('change-pass', 'ProfileController@change_pass')->name('change_pass.store');
    Route::get('/charge-wallet', '\App\Http\Controllers\General\PaymentController@chargeWallet')->name('charge_wallet.view');
    Route::get('tickets', 'TicketController@index')->name('ticket.index');
    Route::get('ticket/new', 'TicketController@create')->name('ticket.create');
    Route::post('ticket', 'TicketController@store')->name('ticket.store');
    Route::get('ticket/{id}', 'TicketController@show')->name('ticket.show');
    Route::post('comment/{id}', 'TicketController@comment')->name('comment.store');
    Route::post('/setting/change_confirmation_type', 'SettingController@change_confirmation_type')->name('setting.change_confirmation_type');
    Route::post('/setting/verify_confirmation_type', 'SettingController@verify_confirmation_type')->name('setting.verify_confirmation_type');
    Route::get('setting', 'SettingController@form')->name('setting.form');
    Route::post('/setting/status-google-authenticator', 'SettingController@status_google_authenticator')->name('setting.status_google_authenticator');
    Route::post('/setting/login_2fa', 'SettingController@login_2fa')->name('setting.login_2fa');

    Route::get('/sell-currency', 'SellBuyController@sellCurrencyView')->name('sell_currency.view');
    Route::post('get-user-assets', 'AssetController@get_user_assets');
    Route::resource('my-wallet', 'AssetController');
    Route::resource('banks', 'BankController')->middleware("can:user-check,bank");
    Route::post('update-profile-picture/{user}', 'ProfileController@update_avatar')->name('profile.update.picture');
    Route::post('/complete-registration', 'ProfileController@completeRegistration')->name('complete-registration');
    Route::post('get-address-wallet', 'AssetController@getAddressWallet')->name('wallet.get-address-wallet');
    Route::post('withdrawal-fee', 'AssetController@WithdrawalFee')->name('wallet.withdrawal-fee');
    Route::post('withdraw', 'AssetController@withdraw')->name('withdraw.store')->middleware(['auth','2fa']);
    Route::post('security-withdraw', 'AssetController@security_withdraw')->name('withdraw.security');
    Route::post('security-send-sms', 'AssetController@security_send_sms')->name('withdraw.send-sms');
    Route::get('transactions','TransactionController@index')->name('transactions.index');
    Route::resource('notification','NotificationController')->names('notification');

    // Shares & Invest Route
//    Route::get('invest/cancel/{invest_shares}', 'Invest_SharesController@cancel')->name('user.invest.cancel');
//    Route::get('invest/add-to-share/{invest_shares}', 'Invest_SharesController@add_to_share')->name('user.invest.add_to_share');
//    Route::get('invest/{invest_shares}/logs', 'Invest_SharesController@logs')->name('user.invest.logs');
    Route::get('shares/{invest_shares}/logs', 'Invest_SharesController@logs')->name('user.shares.logs');
//    Route::resource('invest', 'Invest_SharesController', ['as' => 'user']);
    Route::resource('shares', 'Invest_SharesController', ['as' => 'user']);
    //== Shares & Invest Route

    Route::get('buy-ctr', 'AssetsController@buy_ctr_view')->name('user.buy-ctr');
    Route::post('buy-ctr', 'AssetsController@buy_ctr_store')->name('user.buy-ctr.store');
    Route::post('assets/{asset_unit}/price-on-usdt', 'AssetsController@price_on_usdt')->name('assets.price_on_usdt');
    Route::post('assets/{asset_unit}/convert-to-usdt', 'AssetsController@convert_to_usdt')->name('assets.convert_to_usdt');

});

app/Models/UserGuard.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class UserGuard extends Model
{
    use HasFactory, SoftDeletes;
    protected $fillable = ["guardable_id", "guardable_type"];

    public function guardable()
    {
        return $this->morphTo(__FUNCTION__, 'guardable_type', 'guardable_id');
    }

    public function getFullnameAttribute()
    {
        $user = $this->user;
        if ($user)
            return $user->first_name . ' ' . $user->last_name;
    }

    public function user()
    {
        return $this->hasOne($this->guardable_type, 'id', 'guardable_id');
    }

    public function getPanelTypeAttribute()
    {
        switch ($this->guardable_type) {
            case "Modules\Admin\Entities\Admin":
                return "ادمین";
                break;
            case "Modules\User\Entities\User":
                return "مشتری";
                break;
        }
    }

    public function posts()
    {
        return $this->hasMany(Post::class);
    }
}

app/Http/Controllers/Landing/HomeController.php
<?php

namespace App\Http\Controllers\Landing;

use App\Http\Controllers\Controller;
use App\Models\Post;
use App\Models\PostCategory;
use Illuminate\Http\Request;
use App\Models\GlobalMarketApi;
use Illuminate\Support\Facades\Session;

class HomeController extends Controller
{
    public function index()
    {
        $currency=GlobalMarketApi::where('type','price_currency')->first();
        return view('landing.main',compact('currency'));
    }

    public function test()
    {
        $user = auth()->user();
        return view('user.test',compact('user'));
    }

    public function about()
    {
        return view('landing.about');
    }

    public function blog(Request $request)
    {
        $posts=Post::query()
            ->where('status',1);
        $request->search && !empty($request->search)?$posts->where('title','like','%'.$request->search.'%'):'';
        $ids=$posts->pluck('category_id')->toArray();
        $categories=PostCategory::withCount(['posts'=>function($q){
            $q->where('status',1);
        }])->where('status',1)->whereIn('id',$ids)->orderBy('posts_count','desc')->limit(5)->get();
        $posts=$posts->paginate(5);
        $new_posts=Post::where('status',1)->latest()->limit(4)->get();
        return view('landing.blog',compact('posts','categories','new_posts'));
    }

    public function post_show($slug)
    {
        $post=Post::where('slug',$slug)->with('post_category')->first();
        return view('landing.desktop.blog_show',compact('post'));
    }

    public function services()
    {
        return view('landing.services');
    }

    public function faq()
    {
        return view('landing.faq');
    }

    public function chart()
    {
        return view('landing.chart');
    }
}

resources/views/landing/desktop/blog.blade.php
@extends('templates.landing_page.layout.desktop.master_page')
@section('title_browser')
    مجله خبری
@endsection
<header class="blog-page-header">
    <div class="container">
        <nav class="nav blog-nav">
            @include('templates.landing_page.layout.desktop.top_menu')
        </nav>
    </div>
</header>
@section('content')
    <!-- Start Section One -->
    <section>
        <div class="container-secondary container-secondary-blog">
            <div class="blog-page-top-slide-container">
                <div class="owl-carousel owl-theme blog-page-top-slide">
                    @if(count($new_posts)>0)
                        @foreach($new_posts as $item)
                            <div class="blog-image-slide-container">
                                <div class="blog-page-top-slide__img">
                                    <img style="width: 920px; height: 460px;"
                                         src="{{$item->blogImage}}"
                                         alt="ارز دیجیتال"
                                    />
                                </div>

                                <div class="blog-page-top-slide__info">
                                    <div class="blog-page-top-slide__title">
                                        <span>{{$item->user_guard->fullname}}</span>
                                        <span>۵ نظر</span>
                                    </div>

                                    <h1>
                                        {{$item->title}}
                                    </h1>

                                    <a href="{{route('landing.post',$item->slug)}}"> بیشتر بخوانید </a>
                                </div>
                            </div>
                        @endforeach
                    @endif
                </div>
            </div>
        </div>
    </section>
    <!-- End Section One -->

    <!-- Start Section Two -->
    <section>
        <div class="container-secondary container-secondary-blog">
            <div class="row blog-row-section-2">
                <div class="col-12 col-md-8">
                    <div class="right-blog-page">
                        @if(count($posts)>0)
                            @foreach($posts as $post)
                                <div class="main-news">
                                    <div class="main-news__image">
                                        <img src="{{$post->blogImage}}" alt="تایتل خبر"/>
                                    </div>

                                    <div class="main-news__info">
                                        <div class="main-news__writer">
                                            <span>{{$post->user_guard->fullname}}</span>
                                            <span>۲۵ نظر</span>
                                        </div>

                                        <h2 class="main-news__title">
                                            {{$post->title}}
                                        </h2>

                                        <p class="main-news__desc">
                                            {!! \Illuminate\Support\Str::limit($post->description,50) !!}
                                        </p>

                                        <a href="{{route('landing.post',$post->slug)}}" class="main-news__btn"> بیشتر
                                            بخوانید </a>
                                    </div>
                                </div>
                            @endforeach
                                <div class="pagination">
                                    {!! $posts->links() !!}
                                    {{--                                <button class="pagination-page">--}}
                                    {{--                                    <svg--}}
                                    {{--                                        xmlns="http://www.w3.org/2000/svg"--}}
                                    {{--                                        width="7.645"--}}
                                    {{--                                        height="12.38"--}}
                                    {{--                                        viewBox="0 0 7.645 12.38"--}}
                                    {{--                                    >--}}
                                    {{--                                        <path--}}
                                    {{--                                            id="Icon_material-expand-more"--}}
                                    {{--                                            data-name="Icon material-expand-more"--}}
                                    {{--                                            d="M19.926,12.885,15.19,17.61l-4.735-4.725L9,14.34l6.19,6.19,6.19-6.19Z"--}}
                                    {{--                                            transform="translate(-12.885 21.38) rotate(-90)"--}}
                                    {{--                                            opacity="0.6"--}}
                                    {{--                                        />--}}
                                    {{--                                    </svg>--}}
                                    {{--                                </button class="pagination-page">--}}
                                    {{--                                <button class="pagination-page">--}}
                                    {{--                                    <span>3</span>--}}
                                    {{--                                </button>--}}
                                    {{--                                <button class="pagination-page active"></button>--}}
                                    {{--                                <button class="pagination-page">1</button>--}}
                                </div>
                        @endif

                    </div>
                </div>

                <div class="col-12 col-md-4" dir="ltr">
                    <div class="left-blog-page">
                        <div class="blog-search">
                            <h3>جست و جو</h3>
                            <form action="{{route('landing.blog')}}" class="left-blog-page__search-form">
                                <input name="search" type="search" placeholder="جست و جو..."/>
                                <button>
                                    <svg
                                        xmlns="http://www.w3.org/2000/svg"
                                        width="18.461"
                                        height="18.461"
                                        viewBox="0 0 18.461 18.461"
                                    >
                                        <g
                                            id="Icon_feather-search"
                                            data-name="Icon feather-search"
                                            transform="translate(0.5 0.5)"
                                            opacity="0.6"
                                        >
                                            <path
                                                id="Path_8461"
                                                data-name="Path 8461"
                                                d="M19.837,12.168A7.668,7.668,0,1,1,12.168,4.5,7.668,7.668,0,0,1,19.837,12.168Z"
                                                transform="translate(-4.5 -4.5)"
                                                fill="none"
                                                stroke="#000"
                                                stroke-linecap="round"
                                                stroke-linejoin="round"
                                                stroke-width="1"
                                            />
                                            <path
                                                id="Path_8462"
                                                data-name="Path 8462"
                                                d="M29.145,29.145l-4.17-4.17"
                                                transform="translate(-11.891 -11.891)"
                                                fill="none"
                                                stroke="#000"
                                                stroke-linecap="round"
                                                stroke-linejoin="round"
                                                stroke-width="1"
                                            />
                                        </g>
                                    </svg>
                                </button>
                            </form>
                        </div>

                        <div class="side-news-container">
                            <h3 class="left-blog-page__title">اخبار جدید</h3>
                            @if(count($new_posts)>0)
                                @foreach($new_posts as $item)
                                    <div class="side-news-container__side-news">
                                        <div class="side-news-container__image">
                                            <img src="{{$item->blogImage}}" alt="تایتل اخبار"/>
                                        </div>
                                        <div class="side-news">
                                            <h4>{{$item->title}}</h4>
                                            <span>{{jdate_from_gregorian($item->created_at)}}</span>
                                        </div>
                                    </div>
                                @endforeach
                            @endif
                        </div>

                        <div class="categories-blog">
                            <h3 class="left-blog-page__title">دسته بندی</h3>
                            <ul class="categories-blog__menu">
                                @if(count($categories)>0)
                                    @foreach($categories as $category)
                                        <li class="categories-blog__item">
                                            <div class="circle-blog-page"></div>
                                            <a href="#" class="categories-blog__link">
                                                {{$category->name}}
                                                <span>{{$category->posts_count}}</span>
                                            </a>
                                        </li>
                                    @endforeach
                                @endif

                            </ul>
                        </div>

                        {{--                        <div class="blog-tags">--}}
                        {{--                            <h3 class="left-blog-page__title">تگ ها</h3>--}}
                        {{--                            <div class="blog-tags__items">--}}
                        {{--                                <a href="#" class="blog-tags__item">رمز ارز,</a>--}}
                        {{--                                <a href="#" class="blog-tags__item">بیت کوین,</a>--}}
                        {{--                                <a href="#" class="blog-tags__item">ترید,</a>--}}
                        {{--                                <a href="#" class="blog-tags__item">بیت مارکت,</a>--}}
                        {{--                                <a href="#" class="blog-tags__item">اتریوم,</a>--}}
                        {{--                                <a href="#" class="blog-tags__item">صرافی,</a>--}}
                        {{--                                <a href="#" class="blog-tags__item">تحلیل</a>--}}
                        {{--                            </div>--}}
                        {{--                        </div>--}}

                        <div class="newsletters-container">
                            <h3 class="left-blog-page__title">خبرنامه آنلاین</h3>

                            <div class="newsletters">
                                <div class="newsletters__desc">
                                    <p>برای دریافت خبرنامه های روتیکس</p>
                                    <p>ایمیل خود را وارد کنید و به روز باشید</p>
                                </div>

                                <form action="#" class="newsletters__form">
                                    <input type="email" placeholder="email address..."/>
                                    <button type="submit" class="newsletters__btn" disabled>
                                        ثبت ایمیل
                                    </button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- End Section Two -->
@endsection
@section('script')

@endsection